### ISSUE TITLE
changes not saving

### ISSUE THREAD

**Issue by portrower8** [mindsharestudios/wp-ultimate-search#1]
i have downloaded the beta version and installed. the problem is when I make changes in settings (in admin) the changes aren't actually retained. I tried changing all kinds of things from replacing wordpress search to adding taxonomy facet or whatever -- none of it sticks. when I try to enable a value under post meta... it acts like it saves but it returns a page w/ nothing on it

**Comment by attackant** [comment]
Thanks for reporting this. We'll test and follow up ASAP.

**Comment by portrower8** [comment]
Thank you so much!  We're going to try to intigrate it into a story sharing site to make it easier for folks to find stories by all kinds of different criteria. very excited about being able to use this!

**Comment by attackant** [comment]
Sorry for the delay. This should be fixed.
