### ISSUE TITLE
Error message on saving settings

### ISSUE THREAD

**Issue by JoPinkish** [mindsharestudios/wp-ultimate-search#3]
I just installed on a local WP, changed a couple of settings and got this warning when saving:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WPUltimateSearchOptions' does not have a method 'record_activation' in C:\xampp\htdocs\mysite\wp-includes\plugin.php on line 213

**Comment by JoPinkish** [comment]
Also these errors:

Firstly on the 'Taxonomy Settings' page:

Warning: Illegal string offset 'taxonomies' in C:\xampp\htdocs\mysite\wp-content\plugins\wp-ultimate-search-master\views\wpus-options.php on line 568

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\mysite\wp-content\plugins\wp-ultimate-search-master\views\wpus-options.php on line 568

---

and then on the Post Type Settings page:

Warning: Illegal string offset 'posttypes' in C:\xampp\htdocs\mysite\wp-content\plugins\wp-ultimate-search-master\views\wpus-options.php on line 752

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\mysite\wp-content\plugins\wp-ultimate-search-master\views\wpus-options.php on line 752

**Comment by attackant** [comment]
This should be fixed. Please grab the latest push.
