### ISSUE TITLE
Buddypress compatibility 

### ISSUE THREAD

**Issue by beatelite** [mindsharestudios/wp-ultimate-search#4]
Does this or will this work with buddypress xprofile fields?

**Comment by attackant** [comment]
I don't know... let us know if you try it.

**Comment by beatelite** [comment]
I does not. Just tested.

**Comment by attackant** [comment]
Ok. Do you know if xprofile fields are stored as standard custom fields?

**Comment by cesasol** [comment]
No they are stored in the database on it's own way. outside the wordpress scope.
